name: Build custom kmods

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: "Kernel version (e.g. 6.6.95-1)"
        required: true
        default: "6.6.95-1"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git unzip wget python3 zstd

      - name: Download ImmortalWrt SDK
        run: |
          wget https://downloads.immortalwrt.org/snapshots/targets/mediatek/filogic/immortalwrt-sdk-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          tar --use-compress-program=unzstd -xf immortalwrt-sdk-*.tar.zst
          for d in immortalwrt-sdk-*; do
          if [ -d "$d" ]; then
            mv "$d" sdk
            break
          fi
          done
          mv immortalwrt-sdk-* sdk

      - name: Patch kernel version
        run: |
          cd sdk
          sed -i "s/^KERNEL_PATCHVER.*/KERNEL_PATCHVER:=${{ github.event.inputs.kernel_version }}/" include/kernel.mk
          echo "LINUX_VERSION-${{ github.event.inputs.kernel_version }} = ${{ github.event.inputs.kernel_version }}" >> include/kernel.mk
          echo "LINUX_KERNEL_HASH-${{ github.event.inputs.kernel_version }} = skip" >> include/kernel.mk
          sed -i 's/+kernel (= .*)//' include/package-defaults.mk
          
      - name: Select kmod packages
        run: |
          cd sdk
          # Автоматически отмечаем нужные kmod
          make defconfig
          # Пример: mt7915e, mt7981-firmware, nf modules
          scripts/feeds install -a
          echo "CONFIG_PACKAGE_kmod-nft-queue=y" >> .config
          

      - name: Update feeds
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build kmod packages
        run: |
          cd sdk
          make package/kernel/linux/modules V=s -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: custom-kmods
          path: sdk/bin/packages/
